version: '3'

services:
  test_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPasswd
    ports:
      - 6001:5432

  dev_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPasswd
    ports:
      - 6002:5432
